//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P042.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P042.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;A&quot;,&quot;ABILITY&quot;,&quot;ABLE&quot;,&quot;ABOUT&quot;,&quot;ABOVE&quot;,&quot;ABSENCE&quot;,&quot;ABSOLUTELY&quot;,&quot;ACADEMIC&quot;,&quot;ACCEPT&quot;,&quot;ACCESS&quot;,&quot;ACCIDENT&quot;,&quot;ACCOMPANY&quot;,&quot;ACCORDING&quot;,&quot;ACCOUNT&quot;,&quot;ACHIEVE&quot;,&quot;ACHIEVEMENT&quot;,&quot;ACID&quot;,&quot;ACQUIRE&quot;,&quot;ACROSS&quot;,&quot;ACT&quot;,&quot;ACTION&quot;,&quot;ACTIVE&quot;,&quot;ACTIVITY&quot;,&quot;ACTUAL&quot;,&quot;ACTUALLY&quot;,&quot;ADD&quot;,&quot;ADDITION&quot;,&quot;ADDITIONAL&quot;,&quot;ADDRESS&quot;,&quot;ADMINISTRATION&quot;,&quot;ADMIT&quot;,&quot;ADOPT&quot;,&quot;ADULT&quot;,&quot;ADVANCE&quot;,&quot;ADVANTAGE&quot;,&quot;ADVICE&quot;,&quot;ADVISE&quot;,&quot;AFFAIR&quot;,&quot;AFFECT&quot;,&quot;AFFORD&quot;,&quot;AFRAID&quot;,&quot;AFTER&quot;,&quot;AFTERNOON&quot;,&quot;AFTERWARDS&quot;,&quot;AGAIN&quot;,&quot;AGAINST&quot;,&quot;AGE&quot;,&quot;AGENCY&quot;,&quot;AGENT&quot;,&quot;AGO&quot;,&quot;AGREE&quot;,&quot;AGREEMENT&quot;,&quot;AHEAD&quot;,&quot;AID&quot;,&quot;A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
    }
}
